# Generated by Django 5.2.7 on 2025-11-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('banned', 'Banned'), ('normal', 'Normal')], default='active', max_length=7),
        ),
    ]
