# Generated by Django 5.2.7 on 2025-12-24 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="feedback.feedback",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True
            ),
        ),
    ]
