# Generated by Django 5.2.7 on 2026-01-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_parent_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('banned', 'Banned'), ('normal', 'Normal')], default='pending', max_length=7),
        ),
    ]
