# Generated by Django 5.2.7 on 2025-12-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=45)),
                ('shop_phone_number', models.CharField(default='', max_length=20)),
                ('shop_address', models.TextField(default='', max_length=200)),
                ('shop_email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
