openapi: 3.0.3
info:
  title: ShopLiteX API
  description: |-
    Tài liệu API cho ShopLieX
    Hỗ trợ 3 vai trò:
    - **Buyer**: Người mua hàng
    - **Seller**: Người bán (chủ shop)
    - **Admin**: Quản trị viên
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000/api/
    description: Dev server
tags:
  - name: Auth
    description: Xác thực người dùng (Đăng nhập, Đăng ký)
  - name: User
    description: Quản lý thông tin người dùng (cho Buyer & Seller)
  - name: Products
    description: Quản lý và duyệt sản phẩm
  - name: Shops
    description: Quản lý và duyệt cửa hàng
  - name: Categories
    description: Quản lý và duyệt danh mục
  - name: Orders
    description: Quản lý đơn hàng (Bills & BillDetail)swagg
  - name: Feedback
    description: Quản lý đánh giá sản phẩm
  - name: Admin
    description: Chức năng quản trị của Admin
  - name: Payment
    description: Xử lý thanh toán
    
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Đăng ký tài khoản mới
      description: Đăng ký tài khoản cho Buyer hoặc Seller.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Đăng ký thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Email hoặc username đã tồn tại
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      tags:
        - Auth
      summary: Đăng nhập
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Sai email hoặc mật khẩu
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/me:
    get:
      tags:
        - User
      summary: Lấy thông tin cá nhân
      description: Lấy thông tin của người dùng đã đăng nhập (Buyer, Seller, Admin).
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Thông tin người dùng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      tags:
        - User
      summary: Cập nhật thông tin cá nhân
      description: Cập nhật thông tin của người dùng đã đăng nhập.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                  example: 'Nguyen Van A Updated'
                email:
                  type: string
                  format: email
                  example: 'buyer_updated@example.com'
      responses:
        '200':
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /shops/my-shop:
    get:
      tags:
        - Shops
      summary: Lấy thông tin shop của tôi (Seller)
      description: Chỉ **Seller** mới xem được thông tin shop của mình.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Thông tin shop
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shop'
    put:
      tags:
        - Shops
      summary: Cập nhật thông tin shop (Seller)
      description: Chỉ **Seller** mới cập nhật được shop của mình.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shop_name:
                  type: string
                  example: 'Shop Quần Áo Siêu Đẹp'
      responses:
        '200':
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shop'
  /products:
    get:
      tags:
        - Products
      summary: Lấy danh sách sản phẩm (Public)
      description: Lấy danh sách tất cả sản phẩm, có thể lọc theo category, shop...
      parameters:
        - name: category_id
          in: query
          schema:
            type: integer
        - name: shop_id
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Danh sách sản phẩm
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      tags:
        - Products
      summary: Thêm sản phẩm mới (Seller)
      description: Chỉ **Seller** mới được thêm sản phẩm vào shop của mình.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProductRequest'
      responses:
        '201':
          description: Thêm sản phẩm thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '403':
          description: Không có quyền (không phải Seller hoặc không sở hữu shop)
  /products/{productId}:
    get:
      tags:
        - Products
      summary: Lấy chi tiết sản phẩm (Public)
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Chi tiết sản phẩm
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    put:
      tags:
        - Products
      summary: Cập nhật sản phẩm (Seller)
      description: Chỉ **Seller** sở hữu sản phẩm mới được cập nhật.
      security:
        - bearerAuth: []
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProductRequest' # Dùng chung schema, nhưng shop_id sẽ bị bỏ qua
      responses:
        '200':
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    delete:
      tags:
        - Products
      summary: Xóa sản phẩm (Seller)
      description: Chỉ **Seller** sở hữu sản phẩm mới được xóa.
      security:
        - bearerAuth: []
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Xóa thành công
  /categories:
    get:
      tags:
        - Categories
      summary: Lấy danh sách danh mục (Public)
      responses:
        '200':
          description: Danh sách danh mục
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
  /orders:
    get:
      tags:
        - Orders
      summary: Lấy lịch sử đơn hàng (Buyer)
      description: "**Buyer** lấy danh sách các đơn hàng (Bills) của mình."
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Danh sách đơn hàng
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags:
        - Orders
      summary: Tạo đơn hàng mới (Buyer)
      description: Buyer tạo đơn hàng mới.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewOrderRequest'
      responses:
        '201':
          description: Đặt hàng thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
  /orders/{orderId}:
    get:
      tags:
        - Orders
      summary: Lấy chi tiết đơn hàng (Buyer)
      description: Buyer xem chi tiết một đơn hàng của mình.
      security:
        - bearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Chi tiết đơn hàng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order' # Schema này cần bao gồm cả BillDetail
  /orders/my-shop:
    get:
      tags:
        - Orders
      summary: Lấy đơn hàng của shop (Seller)
      description: Seller xem các sản phẩm (BillDetail) đã được đặt hàng từ shop của mình.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Danh sách các mục trong đơn hàng của shop
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderDetail'
  /products/{productId}/feedback:
    get:
      tags:
        - Feedback
      summary: Lấy đánh giá của sản phẩm (Public)
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Danh sách đánh giá
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feedback'
    post:
      tags:
        - Feedback
      summary: Thêm đánh giá (Buyer)
      description: Buyer thêm đánh giá cho sản phẩm đã mua.
      security:
        - bearerAuth: []
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                  example: 5
                review:
                  type: string
                  example: 'Sản phẩm rất tốt!'
      responses:
        '201':
          description: Gửi đánh giá thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feedback'
  /admin/users:
    get:
      tags:
        - Admin
      summary: Lấy tất cả người dùng (Admin)
      description: Chỉ **Admin** mới có quyền này.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Danh sách người dùng
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /admin/users/{userId}:
    put:
      tags:
        - Admin
      summary: Cập nhật người dùng (Admin)
      description: Chỉ **Admin** mới có quyền này. Dùng để thay đổi 'role' hoặc 'status'.
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
                  enum: [buyer, seller, admin]
                status:
                  type: string
                  enum: [active, banned, pending]
      responses:
        '200':
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      tags:
        - Admin
      summary: Xóa người dùng (Admin)
      description: Chỉ **Admin** mới có quyền này.
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Xóa thành công
  /admin/categories:
    post:
      tags:
        - Admin
      summary: Tạo danh mục mới (Admin)
      description: Chỉ **Admin** mới có quyền này.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category_name:
                  type: string
                  example: 'Đồ gia dụng'
      responses:
        '201':
          description: Tạo thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
  /admin/categories/{categoryId}:
    put:
      tags:
        - Admin
      summary: Cập nhật danh mục (Admin)
      description: Chỉ **Admin** mới có quyền này.
      security:
        - bearerAuth: []
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category_name:
                  type: string
                  example: 'Đồ gia dụng thông minh'
      responses:
        '200':
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
    delete:
      tags:
        - Admin
      summary: Xóa danh mục (Admin)
      description: Chỉ **Admin** mới có quyền này.
      security:
        - bearerAuth: []
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Xóa thành công


components:
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: integer
          example: 1
        user_name:
          type: string
          example: 'Nguyen Van A'
        email:
          type: string
          format: email
          example: 'buyer@example.com'
        role:
          type: string
          enum: [buyer, seller, admin]
          example: 'buyer'
        status:
          type: string
          enum: [active, banned]
          example: 'active'
    Shop:
      type: object
      properties:
        shop_id:
          type: integer
          example: 1
        shop_name:
          type: string
          example: 'Shop Của Tui'
        owner_id:
          type: integer
          example: 2 # user_id của seller
    Category:
      type: object
      properties:
        category_id:
          type: integer
          example: 1
        category_name:
          type: string
          example: 'Thời trang nam'
    Product:
      type: object
      properties:
        product_id:
          type: integer
          example: 101
        name:
          type: string
          example: 'Áo sơ mi'
        description:
          type: string
          example: 'Áo sơ mi vải lụa'
        price:
          type: number
          format: decimal
          example: 250000.00
        quantity:
          type: integer
          example: 100
        shop_id:
          type: integer
          example: 1
        category_id:
          type: integer
          example: 1
    Feedback:
      type: object
      properties:
        feedback_id:
          type: integer
          example: 1
        rating:
          type: integer
          example: 5
        review:
          type: string
          example: 'Sản phẩm tốt'
        user_id:
          type: integer
          example: 1
        product_id:
          type: integer
          example: 101
    Order:
      type: object
      properties:
        order_id:
          type: integer
          example: 50
        user_id:
          type: integer
          example: 1
        total_price:
          type: number
          format: float
          example: 500000.00
        status:
          type: string
          enum: [pending, shipped, delivered, cancelled]
          example: 'pending'
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderDetail'
    OrderDetail:
      type: object
      properties:
        order_id:
          type: integer
          example: 50
        product_id:
          type: integer
          example: 101
        quantity:
          type: integer
          example: 2
        price:
          type: number
          format: float
          example: 250000.00 # Giá tại thời điểm mua
        shop_id:
          type: integer
          example: 1
    RegisterRequest:
      type: object
      required:
        - user_name
        - email
        - password
        - role
      properties:
        user_name:
          type: string
          example: 'Nguyen Van A'
        email:
          type: string
          format: email
          example: 'new_user@example.com'
        password:
          type: string
          format: password
          example: 'MatKhau@123'
        role:
          type: string
          enum: [buyer, seller]
          example: 'buyer'
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: 'buyer@example.com'
        password:
          type: string
          format: password
          example: 'MatKhau@123'
    AuthResponse:
      type: object
      properties:
        token:
          type: string
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
        user:
          $ref: '#/components/schemas/User'
    NewProductRequest:
      type: object
      required:
        - name
        - price
        - quantity
        - category_id
      properties:
        name:
          type: string
          example: 'Quần Jeans'
        description:
          type: string
          example: 'Quần jeans rách gối'
        price:
          type: number
          format: decimal
          example: 450000.00
        quantity:
          type: integer
          example: 50
        category_id:
          type: integer
          example: 1
    NewOrderRequest:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              product_id:
                type: integer
                example: 101
              quantity:
                type: integer
                example: 2
    Error:
      type: object
      properties:
        message:
          type: string
          example: 'Đã có lỗi xảy ra'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: [] # Yêu cầu xác thực JWT cho tất cả các endpoint (có thể override ở từng endpoint)