# Generated by Django 5.2.7 on 2026-01-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
