# Generated by Django 5.2.7 on 2025-11-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_path',
            field=models.FilePathField(default='None'),
        ),
    ]
