# Generated by Django 5.2.7 on 2026-01-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productvariant_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
    ]
