# Generated by Django 5.2.7 on 2025-11-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_file',
        ),
        migrations.AddField(
            model_name='productimage',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
