# Generated by Django 5.2.7 on 2025-12-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_price_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
    ]
