# Generated by Django 5.2.7 on 2025-12-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_status_orderdetail_order_status_and_more'),
        ('product', '0007_remove_product_price_remove_product_quantity_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='product.product'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='shop.shop'),
        ),
    ]
