# Generated by Django 5.2.7 on 2025-12-14 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderdetail_product_alter_orderdetail_shop'),
        ('product', '0008_remove_productvariant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productvariant'),
        ),
    ]
