# Generated by Django 5.2.7 on 2025-12-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderdetail_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='payment_type',
            field=models.CharField(choices=[('VNPAY', 'VNPAY'), ('COD', 'COD')], default='COD', max_length=5),
        ),
    ]
